on:
  push:
    branches:
      - "main"

jobs:
  analyze:
    name: Analyze JavaScript and TypeScript
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript,typescript
      - name: Build CodeQL database
        uses: github/codeql-action/autobuild@v3