name: CI/CD - DEV - Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: cypress/included:13.14.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: details
        run: npm fund

      - name: node version
        run: node --version
      
  Tests:
      runs-on: ubuntu-24.04
      container:
        image: cypress/included:13.14.0
      steps:
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Install dependencies
         run: npm install
       - name: Cypress version
         run: npx cypress --version